spring:
  application:
    name: spring-boot-jpa-docker
server:
  port: 8070
---

spring:
  application:
    name: spring-boot-jpa-docker
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      time_zone: UTC
      javax:
        persistence:
          query:
            timeout: 600000
  datasource:
    url: jdbc:mysql://localhost:3306/docker?useUnicode=true&useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver




  flyway:
    url: jdbc:mysql://localhost:3306/docker?useUnicode=true&useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    schemas: docker
    user: root
    password: 123456
    baseline-on-migrate: true
    enabled: true








